version: '3'
services:
  goapi:
    image: golang:1.12
    volumes:
      - ./:/go/src/github.com/nqd/golang-w2
    working_dir: /go/src/github.com/nqd/golang-w2
    ports:
      - "8080:8080"
    dns: 8.8.8.8
    command: go run main.go -p 8080
    restart: always
    depends_on:
      - postgresql

  postgresql:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
    - ./migration/schema.sql:/docker-entrypoint-initdb.d/init.sql

  prometheus:
    build: ./prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - /prometheus
    ports:
      - "9090:9090"
    links:
      - goapi
    restart: always

  grafana:
    image: olivernadj/secret-api-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 5ecret
    volumes:
      - /var/lib/grafana
    ports:
      - 3000:3000
    links:
      - prometheus
    restart: always