/*
 * Secret Server
 *
 * This is an API of a secret service. You can save your secret by using the API. You can restrict the access of a secret after the certen number of views or after a certen period of time.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package handlers

import (
	"encoding/json"
	"net/http"
	"time"

	"github.com/dchest/uniuri"
)

type secretIn struct {
	Secret           string
	ExpireAfterViews int32
	ExpireAfter      int32
}

func AddSecret(w http.ResponseWriter, r *http.Request) {
	decoder := json.NewDecoder(r.Body)
	var in secretIn

	err := decoder.Decode(&in)
	if err != nil {
		w.WriteHeader(http.StatusUnprocessableEntity)
		return
	}
	defer r.Body.Close()

	// generate a random key

	out := Secret{
		Hash:           uniuri.New(),
		SecretText:     in.Secret,
		CreatedAt:      time.Now(),
		ExpiresAt:      time.Now().Add(time.Minute * time.Duration(in.ExpireAfter)),
		RemainingViews: in.ExpireAfterViews,
	}

	out.Create()

	outS, _ := json.Marshal(out)

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	w.Write(outS)
}

func GetSecretByHash(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
